"""Safe shared contract for profile TDL diagnostic results."""

PROFILE_TDL_DIAGNOSTIC_CODES = frozenset({
    "OK",
    "PROFILE_NAME_INVALID",
    "PROFILE_IDENTITY_MISSING",
    "PROFILE_IDENTITY_INVALID",
    "PROFILE_IDENTITY_UNSAFE",
    "PROFILE_SESSION_UNSAFE",
    "PROFILE_SESSION_UNREADABLE",
    "PROFILE_ROOT_SESSION_MISSING",
    "PROFILE_USER1_SESSION_MISSING",
    "PROFILE_ROOT_SESSION_DATABASE_MISSING",
    "PROFILE_USER1_SESSION_DATABASE_MISSING",
    "PROFILE_ROOT_SESSION_TDL_INVALID",
    "PROFILE_USER1_SESSION_TDL_INVALID",
    "PROFILE_SESSION_METADATA_MISMATCH",
    "PROFILE_SESSION_IDENTITY_MISMATCH",
    "PROFILE_SESSION_BUSY",
    "PROFILE_SESSION_UNAVAILABLE",
    "WORKER_UPDATE_REQUIRED",
})
