<script lang="ts">
  import { onMount } from 'svelte'; import { api, post, remove } from '$lib/api'; import JobTable from './JobTable.svelte';
  let sources = $state<any[]>([]); let labels = $state<string[]>([]); let chatRef = $state(''); let startId = $state('1'); let label = $state(''); let selected = $state(''); let message = $state('');
  async function load() { const [sourceResult, labelResult] = await Promise.all([api<any>('/sources'), api<any>('/labels')]); sources = sourceResult.items || []; labels = labelResult.items || []; }
  function choose(value: string) { selected = value; const found = sources.find((source) => source.chat_ref === value); if (found) { chatRef = found.chat_ref; startId = String(Number(found.last_id || 0) + 1); label = found.label || ''; } }
  async function submit() { try { await post('/exports', { chat_ref: chatRef, start_id: Number(startId), label: label || undefined }); message = 'Export masuk antrean.'; await load(); } catch (err) { message = err instanceof Error ? err.message : 'Export gagal dibuat.'; } }
  onMount(load);
</script>
<header><p class="text-sm font-bold tracking-[.2em] text-indigo-300">EXPORT</p><h1 class="mt-2 text-3xl font-black">Source & pembuatan export</h1><p class="muted mt-2">Pilih source tersimpan atau masukkan username/numeric chat ID.</p></header><div class="mt-7 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><section class="card p-5"><h2 class="font-bold">Export baru</h2><label class="mt-4 block text-sm font-semibold">Pilih source tersimpan<select class="field mt-1" value={selected} onchange={(event) => choose((event.currentTarget as HTMLSelectElement).value)}><option value="">Source baru…</option>{#each sources as source}<option value={source.chat_ref}>{source.label ? `${source.label} — ` : ''}{source.chat_ref} (berikutnya: {Number(source.last_id) + 1})</option>{/each}</select></label><label class="mt-3 block text-sm font-semibold">Username atau chat ID<input class="field mt-1" bind:value={chatRef} placeholder="username atau -100..." /></label><label class="mt-3 block text-sm font-semibold">Start message ID<input class="field mt-1" type="number" min="1" bind:value={startId} /></label><label class="mt-3 block text-sm font-semibold">Label<input class="field mt-1" list="labels" bind:value={label} placeholder="opsional" /><datalist id="labels">{#each labels as item}<option value={item}></option>{/each}</datalist></label><button class="button mt-5 w-full" onclick={submit}>Mulai export</button>{#if message}<p class="mt-3 text-sm text-indigo-200">{message}</p>{/if}</section><section class="card p-5"><div class="flex items-center justify-between"><h2 class="font-bold">Source tersimpan</h2><span class="badge">{sources.length} source</span></div><div class="mt-4 divide-y divide-slate-800">{#each sources as source}<div class="flex items-center justify-between gap-3 py-3"><button class="text-left" onclick={() => choose(source.chat_ref)}><b>{source.chat_ref}</b><p class="muted text-sm">{source.label || '-'} · last ID {source.last_id}</p></button><button class="text-rose-300" onclick={async () => { await remove(`/sources/${encodeURIComponent(source.chat_ref)}`); await load(); }}>Hapus</button></div>{:else}<p class="muted py-8 text-center">Belum ada source.</p>{/each}</div></section></div><JobTable kind="export" title="Riwayat export" />
