<script lang="ts">
  import { onMount } from 'svelte'; import { api, post } from '$lib/api'; import JobTable from './JobTable.svelte';
  let { section }: { section: 'downloads'|'utility'|'storage'|'workers'|'backups'|'settings' } = $props();
  const meta: Record<string, { title: string; description: string; endpoint: string; job?: string }> = { downloads: { title: 'Download manager', description: 'Antrean JSON, progress, dan histori download.', endpoint: '/downloads/artifacts', job: 'download' }, utility: { title: 'Utility workspace', description: 'Folder, pengaturan default, dan riwayat operasi.', endpoint: '/utility/folders', job: 'utility' }, storage: { title: 'Storage katalog', description: 'Cari katalog, upload folder workspace, dan kelola metadata.', endpoint: '/storage/items?limit=50', job: 'storage_upload' }, workers: { title: 'Workers', description: 'Endpoint worker dan route profile aktif.', endpoint: '/workers' }, backups: { title: 'Backup', description: 'Status backup terenkripsi per node.', endpoint: '/backups/status' }, settings: { title: 'Pengaturan', description: 'Default utility dan informasi sistem.', endpoint: '/utility/settings' } };
  let data = $state<any>(null); let error = $state(''); let query = $state(''); let path = $state(''); let folder = $state(''); let keywords = $state(''); let operation = $state('pindah');
  async function load() { try { const endpoint = section === 'storage' && query ? `/storage/items?q=${encodeURIComponent(query)}&limit=50` : meta[section].endpoint; data = await api<any>(endpoint); error = ''; } catch (err) { error = err instanceof Error ? err.message : 'Gagal memuat data.'; } }
  async function action() { if (section === 'backups') await post('/backups'); if (section === 'utility' && path) await post('/utility/jobs', { utility: operation, folders: [path] }); if (section === 'storage' && path) await post('/storage/uploads', { folder_path: path, folder, keywords }); await load(); }
  onMount(load);
</script>
<header><p class="text-sm font-bold tracking-[.2em] text-indigo-300">{section.toUpperCase()}</p><h1 class="mt-2 text-3xl font-black">{meta[section].title}</h1><p class="muted mt-2">{meta[section].description}</p></header><section class="card mt-7 p-5">{#if section === 'storage'}<div class="flex flex-wrap gap-2"><input class="field min-w-52 flex-1" bind:value={query} placeholder="Cari nama, folder, atau keyword" onkeydown={(event) => event.key === 'Enter' && load()}/><button class="button" onclick={load}>Cari</button></div><div class="mt-4 grid gap-2 md:grid-cols-3"><input class="field" bind:value={path} placeholder="Folder workspace untuk upload"/><input class="field" bind:value={folder} placeholder="Folder logis"/><input class="field" bind:value={keywords} placeholder="Keywords opsional"/></div><button class="button mt-3" onclick={action}>Upload folder</button>{:else if section === 'utility'}<div class="grid gap-2 md:grid-cols-[1fr_auto]"><input class="field" bind:value={path} placeholder="Pilih path dari workspace tree"/><select class="field" bind:value={operation}><option value="pindah">Pindah / group</option><option value="compress">Compress 7z</option><option value="extract">Extract</option><option value="export">Organizer export</option></select></div><button class="button mt-3" onclick={action}>Jalankan utility</button>{:else if section === 'backups'}<button class="button" onclick={action}>Backup sekarang</button>{/if}{#if error}<p class="mt-4 text-sm text-rose-300">{error}</p>{/if}<pre class="mt-5 max-h-[38rem] overflow-auto rounded-xl bg-[#080d18] p-4 text-xs leading-6">{JSON.stringify(data, null, 2)}</pre></section>{#if meta[section].job}<JobTable kind={meta[section].job} title="Riwayat & progress" />{/if}
