<script lang="ts">
  import { onMount } from 'svelte';
  import { page } from '$app/state';
  import { session } from '$lib/session.svelte';
  import Login from './Login.svelte';
  import { Activity, Archive, Boxes, Download, FileDown, HardDrive, LayoutDashboard, Settings, SlidersHorizontal, Users, Wrench } from '@lucide/svelte';
  const links = [{ href: '/', label: 'Ringkasan', icon: LayoutDashboard }, { href: '/exports/', label: 'Export', icon: FileDown }, { href: '/downloads/', label: 'Download', icon: Download }, { href: '/utility/', label: 'Utility', icon: Wrench }, { href: '/storage/', label: 'Storage', icon: HardDrive }, { href: '/activity/', label: 'Aktivitas', icon: Activity }, { href: '/workers/', label: 'Workers', icon: Users }, { href: '/backups/', label: 'Backup', icon: Archive }, { href: '/settings/', label: 'Pengaturan', icon: Settings }];
  onMount(() => { session.restore(); });
</script>

{#if session.loading}<main class="grid min-h-screen place-items-center"><span class="muted">Memuat sesi aman…</span></main>{:else if !session.current.authenticated}<Login />{:else}<div class="min-h-screen lg:grid lg:grid-cols-[250px_1fr]"><aside class="border-b border-slate-800 bg-[#0b1020] p-4 lg:border-b-0 lg:border-r"><div class="mb-8 flex items-center gap-3 px-2"><div class="grid size-10 place-items-center rounded-xl bg-indigo-500"><Boxes /></div><div><b>tme3</b><p class="muted text-xs">Control center</p></div></div><nav class="grid gap-1">{#each links as link}<a class:active={page.url.pathname === link.href || (link.href !== '/' && page.url.pathname.startsWith(link.href))} class="nav" href={link.href}><svelte:component this={link.icon} size={18}/>{link.label}</a>{/each}</nav><div class="mt-8 card p-3 text-sm"><span class="muted">Worker aktif</span><b class="mt-1 block">{session.current.actor?.worker_route || '-'}</b></div></aside><main class="min-w-0"><header class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 bg-[#0b1020cc] px-5 py-4"><div class="flex items-center gap-3"><select class="field w-auto" value={session.current.actor?.profile} onchange={(event) => session.chooseProfile((event.currentTarget as HTMLSelectElement).value)}>{#each session.current.profiles as profile}<option value={profile}>{profile}</option>{/each}</select><span class="badge succeeded">Backend online</span></div><div class="flex items-center gap-3"><span class="muted text-sm">{session.current.actor?.telegram_user_id}</span><button class="button secondary" onclick={() => session.logout()}>Keluar</button></div></header><section class="mx-auto max-w-7xl p-5 md:p-8"><slot /></section></main></div>{/if}

<style>.nav{display:flex;align-items:center;gap:.7rem;padding:.72rem .8rem;border-radius:.65rem;color:#aebddb;text-decoration:none}.nav:hover,.nav.active{background:#292465;color:#fff}</style>
