<script lang="ts">
  import { onMount } from 'svelte';
  import { Modal } from 'flowbite-svelte';
  import { api, patch, post, remove } from '$lib/api';
  import { session } from '$lib/session.svelte';
  import { formatBytes, formatDate } from '$lib/presentation';
  import WorkspaceExplorer from './WorkspaceExplorer.svelte';
  import JobTable from './JobTable.svelte';
  import { ExternalLink, HardDrive, Pencil, Search, Send, Trash2, Upload } from '@lucide/svelte';
  type Item = { id:string; display_name:string; original_name:string; folder?:string; keywords?:string; file_size?:number; mime_type?:string; owner_user_id?:number; owner_profile?:string; uploaded_at?:string; status?:string };
  let selectedFolder = $state<string[]>([]); let logicalFolder = $state(''); let keywords = $state(''); let query = $state('');
  let items = $state<Item[]>([]); let total = $state(0); let message = $state(''); let pending = $state(false);
  let editing = $state<Item|null>(null); let deleting = $state<Item|null>(null); let displayName = $state(''); let editFolder = $state(''); let editKeywords = $state('');
  const owns = (item: Item) => item.owner_user_id === session.current.actor?.telegram_user_id;
  async function load() { try { const result = await api<{items:Item[];total?:number}>(`/storage/items?q=${encodeURIComponent(query)}&limit=100`); items = result.items || []; total = result.total ?? items.length; } catch (cause) { message = cause instanceof Error ? cause.message : 'Katalog gagal dimuat.'; } }
  async function upload() { pending = true; try { await post('/storage/uploads', { folder_path:selectedFolder[0], folder:logicalFolder, keywords }); message = 'Upload storage masuk antrean.'; } catch (cause) { message = cause instanceof Error ? cause.message : 'Upload gagal.'; } finally { pending = false; } }
  function edit(item: Item) { editing = item; displayName = item.display_name; editFolder = item.folder || ''; editKeywords = item.keywords || ''; }
  async function save() { if (!editing) return; const body:any = {display_name:displayName}; if (owns(editing)) { body.folder = editFolder; body.keywords = editKeywords; } await patch(`/storage/items/${editing.id}`, body); editing = null; await load(); }
  async function destroy() { if (!deleting) return; await remove(`/storage/items/${deleting.id}`); deleting = null; await load(); }
  async function deliver(item: Item) { await post(`/storage/items/${item.id}/deliveries`, {method:'telegram'}); message = `${item.display_name} dikirim ke Telegram.`; }
  async function deepLink(item: Item) { const result = await api<{url:string}>(`/storage/items/${item.id}/deep-link`); window.open(result.url, '_blank', 'noopener,noreferrer'); }
  onMount(load);
</script>
<header class="flex flex-wrap items-end justify-between gap-4"><div><p class="eyebrow">STORAGE</p><h1 class="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Storage channel</h1><p class="muted mt-2">Upload folder workspace, cari katalog, dan kirim file melalui Telegram.</p></div><div class="page-icon"><HardDrive size={23}/></div></header>
<div class="mt-7 grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><section class="card p-5 sm:p-6"><h2 class="font-extrabold">Upload folder</h2><p class="muted mb-4 mt-1 text-sm">Folder dibaca langsung dari worker aktif.</p><WorkspaceExplorer bind:selected={selectedFolder} single/><div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="text-sm font-bold">Folder logis<input class="field mt-2" bind:value={logicalFolder} placeholder="2021jsa"/></label><label class="text-sm font-bold">Keywords<input class="field mt-2" bind:value={keywords} placeholder="javascript, archive"/></label></div><button class="button mt-4" onclick={upload} disabled={!selectedFolder.length || !logicalFolder || pending}><Upload size={16}/>{pending ? 'Menambahkan...' : 'Upload folder'}</button></section>
<section class="card p-5 sm:p-6"><h2 class="font-extrabold">Cari katalog</h2><div class="mt-4 flex gap-2"><input class="field" bind:value={query} placeholder="Nama, folder, keyword..." onkeydown={(event) => event.key === 'Enter' && load()}/><button class="button secondary" onclick={load}><Search size={16}/></button></div><p class="muted mt-3 text-sm">{total} file ditemukan.</p>{#if message}<p class="mt-3 rounded-xl bg-[var(--brand-soft)] p-3 text-sm">{message}</p>{/if}</section></div>
<section class="card mt-5 overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[900px] text-left text-sm"><thead class="border-b border-[var(--line)] text-xs uppercase text-[var(--muted)]"><tr><th class="p-4">File</th><th>Folder/keyword</th><th>Ukuran</th><th>Uploader</th><th>Tanggal</th><th class="pr-4 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-[var(--line)]">{#each items as item}<tr class="hover:bg-[var(--brand-soft)]/30"><td class="p-4"><b>{item.display_name}</b><p class="muted mt-1">{item.original_name}</p></td><td><b>{item.folder || '-'}</b><p class="muted mt-1">{item.keywords || '-'}</p></td><td>{formatBytes(item.file_size)}</td><td>{item.owner_profile || '-'}{#if owns(item)}<span class="badge succeeded ml-2">Milik saya</span>{/if}</td><td>{formatDate(item.uploaded_at)}</td><td class="pr-4"><div class="flex justify-end gap-1"><button class="button secondary" onclick={() => deliver(item)}><Send size={14}/>Kirim</button><button class="button ghost" onclick={() => deepLink(item)} title="Deep link"><ExternalLink size={15}/></button><button class="button ghost" onclick={() => edit(item)}><Pencil size={15}/></button>{#if owns(item)}<button class="button ghost text-rose-600" onclick={() => deleting = item}><Trash2 size={15}/></button>{/if}</div></td></tr>{:else}<tr><td colspan="6" class="py-14 text-center muted">Katalog kosong.</td></tr>{/each}</tbody></table></div></section>
<JobTable kind="storage_upload" title="Progress upload storage"/>
<Modal open={Boolean(editing)} onclose={() => editing = null} title="Edit metadata" size="md">{#if editing}<div class="space-y-3"><label class="block text-sm font-bold">Nama tampilan<input class="field mt-2" bind:value={displayName}/></label><label class="block text-sm font-bold">Folder<input class="field mt-2" bind:value={editFolder} disabled={!owns(editing)}/></label><label class="block text-sm font-bold">Keywords<input class="field mt-2" bind:value={editKeywords} disabled={!owns(editing)}/></label>{#if !owns(editing)}<p class="muted text-xs">Semua user boleh rename. Folder dan keyword hanya dapat diubah pemilik.</p>{/if}</div><div class="mt-5 flex justify-end gap-2"><button class="button secondary" onclick={() => editing = null}>Batal</button><button class="button" onclick={save}>Simpan</button></div>{/if}</Modal>
<Modal open={Boolean(deleting)} onclose={() => deleting = null} title="Hapus file storage?" size="sm"><p>Message channel dan metadata <b>{deleting?.display_name}</b> akan dihapus.</p><div class="mt-5 flex justify-end gap-2"><button class="button secondary" onclick={() => deleting = null}>Batal</button><button class="button danger" onclick={destroy}>Hapus</button></div></Modal>
